server:
  port: 5001
#应用名称已验证账号
spring:
  application:
    name: service-jms-consumer
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    jms:
      pub-sub-domain: true

eureka:
  server:
    enable-self-preservation: false #关闭保护机制
    eviction-interval-timer-in-ms: 2000 #提出失败服务间隔，单位毫秒
  client:
    service-url: #设置服务注册中心的URL
      defaultZone: http://root:root@eureka-7901:7901/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1 #服务刷新时间配置，每个这个时间会主动心跳一次
    lease-expiration-duration-in-seconds: 1 #服务过期时间配置，超过这个时间没有接受到心跳EurekaServer就会将这个实例剔除
    hostname: localhost
    prefer-ip-address: true
    status-page-url: /actuator/info #eureka注册中心的URL link
    health-check-url-path: /actuator/health #健康监测的URL
    instance-id: service-jms-consumer
    metadata-map:
      user.name: root
      user.password: root

#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always