# 应用名称
spring:
  application:
    name: cloud-eureka


eureka:
  server:
    enable-self-preservation: true   #自我保护机制
    renewal-percent-threshold: 0.85   #自我保护阔值
    eviction-interval-timer-in-ms: 1000   #拉取到不可用的服务
    #多级缓存（false）默认是true，关闭从readOnly读注册表，是否开启readOnly读缓存
    use-read-only-response-cache: true
    #readWrite和readOnly同步时间间隔
    response-cache-update-interval-ms: 1000
    # spring-cloud中注册表同步重试次数默认为0
    registry-sync-retries: 5

---
spring:
  profiles: eureka-7900
server:
  port: 7900
eureka:
  instance:
    hostname: eureka-7900 # eureka服务端的实例名称
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/

---
spring:
  profiles: eureka-7901
server:
  port: 7901
eureka:
  instance:
    hostname: eureka-7901
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/
---
spring:
  profiles: eureka-7902
server:
  port: 7902
eureka:
  instance:
    hostname: eureka-7902
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/,http://eureka-7901:7901/eureka/,http://eureka-7902:7902/eureka/