# 应用名称已验证账号
spring:
  application:
    name: api-driver
    admin:
      enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
  # zipkin
  zipkin:
    base-url: http://localhost:9411/
    # 采样比例1，百分之百采样，0.1=10%
  sleuth:
    sampler:
      rate: 1
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka-7900:7900/eureka/
    healthcheck:
      enabled: false

# 正常ribbon
ribbon:
  eager-load:
    enabled: true
    clients:
      - SERVICE-SMS
      - SERVICE-VERIFICATION-CODE
  http:
    client:
      enabled: false
  okhttp:
    enabled: false

#Ribbon独立使用时
#service-sms:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    eureka:
#      enable: false
#    listOfServers: localhost:8002, localhost:8003

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        ##默认是never
        show-details: ALWAYS
        enabled: true

logging:
  level:
    root: info
    org.springframework: info



---
spring:
  profiles: 9002
#服务端口
server:
  port: 9002
---
spring:
  profiles: 9003
#服务端口
server:
  port: 9003

