# 应用名称
spring:
  application:
    name: service-sms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MYSQL的驱动程序类
    url: jdbc:mysql://localhost:3306/online-taxi?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai #数据库链接地址
    username: root
    password: root
    dbcp2: # 进行数据库连接池的配置
      initial-size: 5 # 初始化提供的连接数
      min-idle: 5 # 数据库连接池的最小维持链接数
      max-total: 5 # 最大的连接数
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
  redis:
    host: loalhoat # Redis服务器地址
    database: 0 #Redis数据库索引（默认为0）
    port: 6379 #Redis服务器连接端口
    password: 123 #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲链接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000ms #连接超时时间（毫秒）
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      host: localhost #mongodb的链接地址
      port: 27017 #MongoDB的连接端口号
      database: service-sms #MongoDB的连接的数据库
  rabbitmq:
    host: localhost #rabbitMQ的链接地址
    port: 5672 #rabbitMQ的连接端口号
    virtual-host: /sms #rabbitMQ的虚拟host
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      rate: 1
  aop:
    auto: true #等价于@EnableAspectJAutoProxy
    proxy-target-class: true #使用CGLIB动态代理

redis:
  database: sms
  key:
    profix:
      authCode: 'portal:authCode'
    expire:
      authCode: 120 #验证码超期时间
#自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间（60*60*24）
  tokenHead: Bearer #JWT负载中拿到开头

#OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com #oss对外服务的访问域名
    accessKeyId: test #访问身份验证中用到用户标识
    accessKeySecret: test #用户用于加密签名字符串和OSS用来验证签名字符串的密钥
    bucketName: macro-oss #oss的存储空间
    policy:
      expire: 300 #签名有效期(S)
    maxSize: 10 #上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback #文件上传成功后的回调地址
    dir:
      prefix: sms/images/ #上传文件夹路径前缀
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.gyh.internalcommon # 定义所有操作类的别名所在包
  mapper-locations:  # 所有的mapper映射文件
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

eureka: #注册中心
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 1 # 服务刷新时间配置，每隔这个时间会主动心跳一次

management: #Admin检测
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.springframework.web.servlet: debug
---
spring:
  profiles: v1

eureka:
  instance:
    metadata-map:
      version: v1
      a: a1
server:
  port: 8003
---
spring:
  profiles: v2

eureka:
  instance:
    metadata-map:
      version: v2
server:
  #服务端口
  port: 8004