# 应用名称
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online-taxi?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,slf4j
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: SELECT 'X'
  activemq:
    broker-url: tcp://localhost:61617
    in-memory: true
    pool:
      enabled: true
      max-connections: 100


apikey:
  ali:
    - pool_key: FC1000xxxxxxxxxx
    - file_path: /tmp
    - key_id: LTAIoC4Iuyxxxx
    - key_secret: jPtxnruaZGJ7HjbSdkwJdxxxxxxx
    - dyplsapi: Dyplsapi
    - domain: dyplsapi.aliyuncs.com
  oss:
    - endpoint: https://oss-cn-hangzhou.aliyuncs.com/
    - access_id: LTAIzbAxxxxxxxxxx
    - access_key: c3rLTtLv4qdR9m8kxxxxxxxxxxxx
    - bucket_taxi: test-source
    - oss_file_name: voiceRecording
    - role_arn: acs:ram::114191736xxxxxxx:role/test-source-write
#internal 程序内部
logging:
  config: classpath:log/logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

pagehelper:
  reasonable: true

#customer
